#!/bin/bash

## Description: Setup the project
## Usage: setup
## Example: "ddev setup"

project_name=$(basename $PWD)

if [ -f .env ]; then
  sed -i 's|APP_URL=.*|APP_URL="http://api.'"$project_name"'"|' .env
fi

cat <<EOL > .ddev/config.yaml
name: $project_name
type: laravel
docroot: public
php_version: "8.1"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames:
  - "api.$project_name"
additional_fqdns: []
database:
  type: mariadb
  version: "10.4"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "18"
EOL

# Step 1: Start DDEV
echo "Step 1: Starting DDEV"
ddev start &&

# Step 2: Install all required Composer dependencies
echo "Step 2: Installing all required Composer dependencies"
ddev composer install &&

# Step 3: Generate a key for your application
echo "Step 3: Generating a key for your application"
ddev exec "php artisan key:generate" &&

# Step 4: Execute Laravel migrations to create the database
echo "Step 4: Executing Laravel migrations to create the database"
ddev artisan migrate &&

# Step 5: Import Pokémon data
echo "Step 5: Importing Pokémon data"
ddev artisan app:import-pokemon-data
